<!DOCTYPE html
    PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN"
    "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html>
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <link href="/public/css/admin.css" rel="stylesheet" />

    <?php echo '<title>'.$this->pageTitle.'</title>'; ?>
    <?php echo $this->headScript() ?>
    <?php echo $this->headLink() ?>
    <script src="http://ajax.googleapis.com/ajax/libs/jquery/1.3.2/jquery.min.js"></script>
    <script src="http://ajax.googleapis.com/ajax/libs/jqueryui/1.7.2/jquery-ui.min.js"></script>
    <?php if ($this->ckeditor) {
        echo $this->headScript()->appendFile(
                 $this->baseUrl().'/public/js/ckeditor/ckeditor.js'
        );
    }?>
</head>
<body>
 

    <div id="nav"><?php echo $this->render('admin/admin_header.phtml') ?></div>
<div class="cl"></div>
    <div id="content"><?php echo $this->layout()->content ?></div>

    <?php //echo $this->render('footer.phtml') ?>
</body>
</html>