<!DOCTYPE html
    PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN"
    "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html>
<head>
    <link rel="icon" href="/public/img/favicon.ico" type="image/x-icon" />
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <?php echo '<title>'.$this->pageTitle.'</title>'; ?>
    <?php echo $this->headScript() ?>
    <?php echo $this->headLink() ?>
    <?php echo $this->headLink()->appendStylesheet($this->baseURL.'/public/css/style.css'); ?> 
    
    <script src="http://ajax.googleapis.com/ajax/libs/jquery/1.3.2/jquery.min.js"></script>
    <script src="http://ajax.googleapis.com/ajax/libs/jqueryui/1.7.2/jquery-ui.min.js"></script>
    	<script type="text/javascript">
		//no conflict jquery
		jQuery.noConflict();
		//jquery stuff
	</script>
    
</head>


    <body class="homepage<?php echo ($this->lang != 'en') ? '_'.$this->lang:''; ?>">
  <div id="container">
    <div id="header"><?php  echo $this->render('helpers/header.phtml') ?>
            <?php  echo $this->render('helpers/menu.phtml') ?>
    </div>
    <div id="wrapper">
      <div id="content"><?php echo $this->layout()->content ?></div>
    </div>
    <div id="navigation"><?php  echo $this->render('helpers/sidebar.phtml') ?></div>
    <div id="footer"><?php echo $this->render('helpers/footer.phtml') ?></div>
    </div>
    <?php echo $this->render('helpers/counter.phtml'); ?>    
</body>
</html>
