<!DOCTYPE html
    PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN"
    "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html>
    <head>
        <link rel="icon" href="/public/img/favicon.ico" type="image/x-icon" />
        <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
        <?php echo '<title>' . $this->pageTitle . '</title>'; ?>
        <?php echo $this->headScript() ?>
        <?php echo $this->headLink() ?>
        <?php echo $this->headLink()->appendStylesheet($this->baseURL . '/public/css/style.css'); ?>

    </head>


    <body >
        <div id="wrapper">

            <div id="header">
                <?php echo $this->render('helpers/header.phtml') ?>
                <?php echo $this->render('helpers/menu.phtml') ?>
            </div><!-- #header-->

            <div id="middle">

                <div id="container">

                    <div id="content">
                       <?php echo $this->layout()->content; ?>
                    </div><!-- #content-->
                </div><!-- #container-->

                <div class="sidebar" id="sideRight">
                    <?php echo $this->render('helpers/sidebar.phtml') ?>
                </div><!-- .sidebar#sideRight -->

            </div><!-- #middle-->

        </div><!-- #wrapper -->

        <div id="footer">
            <?php echo $this->render('helpers/footer.phtml') ?>
        </div><!-- #footer -->

    </body>
</html>
