<h1><?php echo $this->post->title; ?></h1>
<hr />

<img src="/public/img/blog/thumb/<?php echo $this->post->identry; ?>.jpg" align="left" style="padding-right: 7px; "/>
<div class="show_blog_entry">

    <?php echo $this->post->richtext; ?>

</div>
<div style="clear: both;"></div>

<?php foreach ($this->comments as $comment) : ?>
    <div class="blog" >
        <div class="blog_title">
        <h2><?php echo $this->escape($comment->name); ?></h2>
        <?php echo $this->localDate($comment->postdate, $this->lang); ?></div>
        <div class="blog_stext2">
            <?php echo $this->escape($comment->message); ?>
        </div>
    </div>
<?php endforeach; ?>

<div style="clear: both;"></div>
<div class="comment">
    <form action="" method="post">    
        <table border="0">
            <tr>
                <td >Від кого:</td>
                <td ><input name="sender" /></td>
            </tr>
            <tr>
                <td>Email:</td>
                <td><input name="email" /></td>
            </tr>
            <tr>
                <td>Повідомлення:</td>
                <td><textarea name="message" ></textarea></td>
            </tr>
            <tr>
                <td><input type="hidden" name="token" value="<?php echo $this->token; ?>" /></td>
                <td><input type="submit" class="slbut" value="Відіслати повідомлення" /></td>
            </tr>
        </table>    
    </form>    
    <div class="textcomment"></div>
    <div class="textinput"></div>

<!--<div class="textcomment">Email:</div><div> <input name="sender" />
</div>

<div class="textcomment">Сообщение:</div> <div><textarea name="message" ></textarea>
</div>-->
</div>    
