<h1><?php echo $this->post->title; ?></h1>
<hr />

<img src="/public/img/blog/thumb/<?php echo $this->post->identry; ?>.jpg" align="left" style="padding-right: 7px; "/>
<div class="show_blog_entry">

    <?php echo $this->post->richtext; ?>

</div>
<div style="clear: both;"></div>
<script type="text/javascript" src="//yandex.st/share/share.js" charset="utf-8"></script>
<div class="yashare-auto-init" data-yashareL10n="<?php echo $this->lang;?>" data-yashareType="none" data-yashareQuickServices="vkontakte,facebook,twitter,odnoklassniki"></div>
<hr />
<?php 
if ($this->comments) :
foreach ($this->comments as $comment) : ?>
    <div class="blog" >
        <div class="blog_title">
        <h2><?php echo $this->escape($comment->name); ?></h2>
        <?php echo $this->localDate($comment->postdate, $this->lang); ?></div>
        <div class="blog_stext2" style=" font-size: 16px;">
            <?php echo $this->escape($comment->message); ?>
        </div>
    </div>
<?php endforeach; 
echo "<hr />";
endif;
?>

<div style="clear: both;"></div>
<?php echo $this->tr(NULL,$this->lang,'<u>Залишити свій відгук</u>'); ?> 
<div  style="margin-top: 12px;">
    <form action="" method="post">    
        <table border="0" class="comment">
            <tr>
                <td ><?php echo $this->tr(NULL,$this->lang,'Від кого:');?></td>
                <td ><input name="name" /></td>
            </tr>
            <tr>
                <td>EMail :<p style="color: rgb(127, 127, 127); font-size: 0.55em; margin: 0pt; padding: 0pt;"><i><?php echo $this->tr(NULL,$this->lang,'не буде показано на сайті');?></i></p></td>
                <td><input name="email" /></td>
            </tr>
            <tr>
                <td><?php echo $this->tr(NULL,$this->lang,'Повідомлення:');?></td>
                <td><textarea style="height: 150px;" name="message" ></textarea></td>
            </tr>
        </table>
        <div style="clear: both;"></div>
        <table>
            <tr>
                <td colspan="2">
                 <br />
                </td>
            </tr>
            <tr>
                <td colspan="2">
                    <?php echo $this->tr(NULL,$this->lang,'Ми маємо перевірити чи Ви реальна людина. <br />Будь-ласка, введіть символи, зображені нижче'); ?> 
                    <?= $this->token->getHTML();?>
                </td>
            </tr>
            <tr>
                <td colspan="2">
                 <br />
                </td>
            </tr>
            <tr>
<!--                <td><input type="hidden" name="token" value="<?php echo $this->token; ?>" /></td>-->
                
                <td><input   class="frm_button_lbut" type="submit" value="<?php echo $this->tr(NULL,$this->lang,'Відіслати повідомлення');?>" /></td>
            </tr>
        </table>    
    </form>    
    <div class="textcomment"></div>
    <div class="textinput"></div>

<!--<div class="textcomment">Email:</div><div> <input name="sender" />
</div>

<div class="textcomment">Сообщение:</div> <div><textarea name="message" ></textarea>
</div>-->
</div>    
