<form action="/<?= $this->lang;?>/blog/new.html">
<input type="submit" class="frm_button_lbut" value="<?php echo $this->tr(NULL,$this->lang,'Створити привітання');?>" />
</form>
<h1><?php echo $this->blogmenu->name;?></h1>
<hr />
<?php
foreach ($this->blogs as $blog) :?>
<div class="blog" >
  
    <div class="blog_title">
          <?php
            $url = array(
                'lang' => $this->lang,
                'title' => Local_String::translit($blog->title),
                'idpost' => $blog->identry
            );
          ?>
          <a href="<?php echo $this->url($url, 'blogpage',true);?>" >
               <h2><?php echo $blog->title;?></h2> 
          </a> <?php echo $this->localDate($blog->date, $this->lang);?></div>
          <a href="<?php echo $this->url($url, 'blogpage');?>" >
            <img src="/public/img/blog/thumb/<?php echo $blog->identry;?>.jpg" align="left"/>
          </a>
    <div class="blog_stext">
        <?php echo mb_substr(strip_tags($blog->richtext),0,280, 'UTF-8');?>
        <a href="<?php echo $this->url($url, 'blogpage',true);?>" style="color: yellow;">
            <?php echo $this->tr(NULL,$this->lang,'Деталі...'); ?>
            <br />
            <i><?php echo $this->tr(NULL,$this->lang,'Коментарів'); ?>: (<?php echo Model_Comment::countComment($blog->identry)->totalcomment;?>)</i>
        </a>
    </div>
</div>

<hr />
<?php
endforeach;

$option = array('lang' => $this->lang);

echo $this->paginationControl($this->blogs,
                             'Sliding',
                             'helpers/pagination.phtml',
                             $option);
?>
<br />
