
<link rel="stylesheet" type="text/css" href="/public/css/sl.css" media="screen" />
<script type="text/javascript" src="/public/js/jquery-1.4.3.min.js"></script>
<script type="text/javascript" src="/public/js/jquery.aslideshow.pack.js"></script>
<script type="text/javascript" src="/public/js/jquery.simplemodal-1.3.4.min.js"></script>



<div style="max-height: 400px;">
<div id="CustomSlideshow">
        <img src="/public/img/main/vesillya.jpg" alt="Весілля"/>

        <img src="/public/img/main/korporativ.jpg" alt="Корпаратив"/>


    <a id="vypuskni" href="/<?php echo $this->lang;?>/vypuskni-vechory-48.html" title="<?php echo $this->tr(NULL,$this->lang,'Випуснкі вечори>'); ?> ">
        <div style="position: relative; background: url('/public/img/main/vyspkni.jpg') no-repeat; width: 720px; height: 400px;">
            <div style="background-color: rgba(0, 0, 0, 0.7);position: absolute;  margin-top:  360px; padding-left: 10px; padding-top: 10px; padding-top: 10px; width: 720px; height: 40px; height: 40px; font-weight: bold; color: #fff;">
                <?php echo $this->tr(NULL,$this->lang,'<h2>Випуснкі вечори</h2>'); ?> </div>

        </div>
    </a>

    <a id="korp" href="/<?php echo $this->lang;?>/korporatyvy-46.html" title="<?php echo $this->tr(NULL,$this->lang,'Корпоративи'); ?>">
        <div style="position: relative; background: url('/public/img/main/korporativ.jpg')  no-repeat; width: 720px; height: 400px;">
            <div style="background-color: rgba(0, 0, 0, 0.7); position: absolute;  margin-top:  360px;  padding-left: 10px; padding-top: 10px; width: 720px; height: 40px; font-weight: bold; color: #fff;">
                <?php echo $this->tr(NULL,$this->lang,'<h2>Корпоративи</h2>'); ?> </div>
        </div>
    </a>

    <a id="konc" href="/<?php echo $this->lang;?>/koncerty-49.html" title="<?php echo $this->tr(NULL,$this->lang,'Концерти'); ?>">
        <div style="position: relative; background: url('/public/img/main/koncert.jpg')  no-repeat; width: 720px; height: 400px;">
            <div style="background-color: rgba(0, 0, 0, 0.7); position: absolute;  margin-top:  360px;  padding-left: 10px; padding-top: 10px; width: 720px; height: 40px; font-weight: bold; color: #fff;">
                <?php echo $this->tr(NULL,$this->lang,'<h2>Концерти</h2>'); ?> </div>
        </div>
    </a>

   <a id="vesi" href="/<?php echo $this->lang;?>/vesillya-45.html" title="<?php echo $this->tr(NULL,$this->lang,'Весілля'); ?>">
        <div style="position: relative; background: url('/public/img/main/vesillya.jpg')  no-repeat; width: 720px; height: 400px;">
            <div style="background-color: rgba(0, 0, 0, 0.7);position: absolute; margin-top:  360px;  padding-left: 10px; padding-top: 10px; width: 720px; height: 40px; font-weight: bold; color: #fff;">
                <?php echo $this->tr(NULL,$this->lang,'<h2>Весілля</h2>'); ?></div>
        </div>
    </a>

    <a id="narod" href="/<?php echo $this->lang;?>/dni-narodzhennya-47.html" title="<?php echo $this->tr(NULL,$this->lang,'Дні народження'); ?>">
        <div style="position: relative; background: url('/public/img/main/birthday.jpg')  no-repeat; width: 720px; height: 400px;">
            <div style="background-color: rgba(0, 0, 0, 0.7);position: absolute; margin-top:  360px;  padding-left: 10px; padding-top: 10px; width: 720px; height: 40px; font-weight: bold; color: #fff;">
                <?php echo $this->tr(NULL,$this->lang,'<h2>Дні народження</h2>'); ?></div>
        </div>
    </a>
    
</div></div>

<div style="clear: both;"></div>
<div style="border-top: 1px white dotted;">
<?php

foreach ($this->last as $blog) :?>
<div class="blog" >
  
    <div class="blog_title">
        
          <?php
            $url = array(
                'lang' => $this->lang,
                'title' => Local_String::translit($blog->title),
                'idpost' => $blog->identry
            );
          ?>
          <a href="<?php echo $this->url($url, 'blogpage');?>" >
               <h2><?php echo $blog->title;?></h2>
          </a> <?php echo $this->localDate($blog->date, $this->lang);?></div>
          <a href="<?php echo $this->url($url, 'blogpage');?>" >
            <img src="/public/img/blog/thumb/<?php echo $blog->identry;?>.jpg" align="left"/>
          </a>
    <div class="blog_stext">
        <?php echo mb_substr(strip_tags($blog->richtext),0,280, 'UTF-8');?>
        <a href="<?php echo $this->url($url, 'blogpage',true);?>" style="color: yellow;">
            <?php echo $this->tr(NULL,$this->lang,'Деталі...'); ?>
        
        <br />
        <i><?php echo $this->tr(NULL,$this->lang,'Коментарів'); ?>: (<?php echo Model_Comment::countComment($blog->identry)->totalcomment;?>)</i>
        </a>
    </div>
</div>

<hr />
<?php
endforeach;?>
</div>



<script type="text/javascript">
//<![CDATA[
$(document).ready(function(){
    $('#CustomSlideshow').slideshow({
        width:720,     // width in px
        height:400,    // height in px
        //history:true,  // change/check location hash
        index:0,       // start from frame number N
        time:2000,     // time out beetwen (ms)
        title:false,   // show title
        panel:false,    // show controls panel
        loop:true,    // stop looping

        effect:'random',      // aviable fade, scrollUp/Down/Left/Right, zoom, zoomFade, zoomTL, zoomBR, growX, growY, random
        effecttime:500,      // aviable fast,slow,normal and any valid fx speed value
        nextclick:false,       // bind content click next slide
        playframe:false,       // show frame "Play Now!"
        imgresize:false       // resize image to slideshow window

    }).playSlide();
});
//]]>
</script>
