
<link rel="stylesheet" type="text/css" href="/public/css/sl.css" media="screen" />
<script type="text/javascript" src="/public/js/jquery-1.4.3.min.js"></script>
<script type="text/javascript" src="/public/js/jquery.aslideshow.pack.js"></script>




<div style="max-height: 400px;">
<div id="CustomSlideshow">
<!--        <img src="/public/img/main/vesillya.jpg" alt="Весілля"/>

        <img src="/public/img/main/korporativ.jpg" alt="Корпаратив"/>-->


    <a href="http://cnn.com" title="Camomile">
        <div style="position: relative; background: url('/public/img/main/vyspkni.jpg') no-repeat; width: 720px; height: 400px;">
            <div style="background-color: rgba(0, 0, 0, 0.7);position: absolute;  margin-top:  340px; padding-left: 10px; width: 720px; height: 60px; height: 60px; font-weight: bold; color: #fff;">
                <p><?php echo $this->tr(NULL,$this->lang,'<h2>Випуснкі вечори</h2>'); ?></p> </div>

        </div>
    </a>

    <a href="http://stb.ua" title="Bumblebees">
        <div style="position: relative; background: url('/public/img/main/korporativ.jpg')  no-repeat; width: 720px; height: 400px;">
            <div style="background-color: rgba(0, 0, 0, 0.7); position: absolute;  margin-top:  340px;  padding-left: 10px; width: 720px; height: 60px; font-weight: bold; color: #fff;">
                <p><?php echo $this->tr(NULL,$this->lang,'<h2>Корпоративи</h2>'); ?></p> </div>
        </div>
    </a>

   <a href="http://stb.ua" title="Bumblebees">
        <div style="position: relative; background: url('/public/img/main/vesillya.jpg')  no-repeat; width: 720px; height: 400px;">
            <div style="background-color: rgba(0, 0, 0, 0.7);position: absolute; margin-top:  340px;  padding-left: 10px; width: 720px; height: 60px; font-weight: bold; color: #fff;">
                <p><?php echo $this->tr(NULL,$this->lang,'<h2>Весілля</h2>'); ?></p> </div>
        </div>
    </a>

    <a href="http://stb.ua" title="Bumblebees">
        <div style="position: relative; background: url('/public/img/main/birthday.jpg')  no-repeat; width: 720px; height: 400px;">
            <div style="background-color: rgba(0, 0, 0, 0.7);position: absolute; margin-top:  340px;  padding-left: 10px; width: 720px; height: 60px; font-weight: bold; color: #fff;">
                <p><?php echo $this->tr(NULL,$this->lang,'<h2>Дні народження</h2>'); ?></p> </div>
        </div>
    </a>
    
</div></div>

<div style="clear: both;"></div>
<?php

foreach ($this->last as $blog) :?>
<div class="blog">
  
    <div class="blog_title">
          <a href="<?php echo $blog->url;?>" >
               <h2><?php echo $blog->title;?></h2> 
          </a> <?php echo $this->localDate($blog->date, $this->lang);?></div>
          <a href="<?php echo $blog->url;?>" >
            <img src="/public/img/blog/thumb/<?php echo $blog->identry;?>.jpg" align="left"/>
          </a>
    <div class="blog_stext">
        <?php echo mb_substr(strip_tags($blog->richtext),0,450, 'UTF-8');?>
    </div>
</div>

<hr />
<?php
endforeach;?>



<script type="text/javascript">
//<![CDATA[
$(document).ready(function(){
    $('#CustomSlideshow').slideshow({
        width:720,     // width in px
        height:400,    // height in px
        //history:true,  // change/check location hash
        index:0,       // start from frame number N
        time:2000,     // time out beetwen (ms)
        title:false,   // show title
        panel:false,    // show controls panel
        loop:true,    // stop looping

        effect:'random',      // aviable fade, scrollUp/Down/Left/Right, zoom, zoomFade, zoomTL, zoomBR, growX, growY, random
        effecttime:500,      // aviable fast,slow,normal and any valid fx speed value
        nextclick:false,       // bind content click next slide
        playframe:false,       // show frame "Play Now!"
        imgresize:false       // resize image to slideshow window

    }).playSlide();
});
//]]>
</script>
