<link rel="stylesheet" type="text/css" href="/public/css/slideshow.css" media="screen" />
<link rel="stylesheet" href="/public/css/mediaboxAdvBlack.css" type="text/css" media="screen" />

<script type="text/javascript" src="http://ajax.googleapis.com/ajax/libs/mootools/1.2.4/mootools-yui-compressed.js"></script>
<script type="text/javascript" src="/public/js/mootools-moon.js"></script>
<script type="text/javascript" src="/public/js/slideshow-moon.js"></script>
<script type="text/javascript" src="/public/js/mediaboxAdv-1.2.0.js"></script>

<?php
$videogallery = $this->render('/helpers/videogallery.phtml');
$imagegallery = $this->render('/helpers/imagegallery.phtml');
$audiogallery = $this->render('/helpers/audiogallery.phtml');
?>

<h1><?php echo $this->escape($this->content->title);?></h1>
<hr />
<?php echo str_replace( array('<!--videogallery-->','<!--imagegallery-->','<!--audiogallery-->'), array($videogallery, $imagegallery,$audiogallery), $this->content->richtext);?>
<?php echo $this->render('/helpers/share.phtml'); ?>