EEEE
<link rel="stylesheet" type="text/css" href="/public/css/sl.css" media="screen" />
<link rel="stylesheet" href="/public/css/mediaboxAdvBlack.css" type="text/css" media="screen" />

<script type="text/javascript" src="http://ajax.googleapis.com/ajax/libs/mootools/1.2.4/mootools-yui-compressed.js"></script>
<script type="text/javascript" src="/public/js/mootools-moon.js"></script>
<script type="text/javascript" src="/public/js/slideshow-moon.js"></script>
<script type="text/javascript" src="/public/js/mediaboxAdv-1.2.0.js"></script>


<script type="text/javascript">
    //<![CDATA[
    window.addEvent('domready', function(){
    var data = {
            <?php
            $i=0;
            foreach ($this->gallery as $image) :
             
             $imagename = $image->idgallery."_".$image->idimage.".jpg";
             ?>

            'mid/<?php echo $imagename;?>': {
                caption: 'Нажмите для просмотра',
                href: "javascript:this.onclick(Mediabox.open('/public/gallery/full/<?php echo $imagename;?>','',''))",
                thumbnail: 'small/<?php echo $imagename;?>'
            }       
            <?php 
            if( ($i+1)!=count($this->gallery) ) {
                          echo  ','; }
            if( ($i == 0) ) {
                $firstimage = '/public/img/ajax-loader.gif';
                //$firstimage = '/gallery/data/gallery_video/'.$image['parent'].'/full/'.$image['file'];
                $firsturl = 'public/gallery/full/'.$imagename;
            }
            $i++;
            endforeach; ?>
        };
        var myShow = new Slideshow('show', data, {controller: false,  hu: '/public/gallery/', paused: true, linked: false, thumbnails: true, delay: 4000, height: 339, width: 509, duration: 750});
    });
    //]]>
</script>
<div id="show" class="slideshow">
    <a href="<?= $firsturl; ?>" id="url"  class="spacing"  title="cation">

        <img  src="<?= $firstimage;?>" width="506" height="339" alt="" />
    </a>
</div>


<h1><?php echo $this->content->title;?></h1>
<hr />
<?php echo $this->content->richtext;?>