EEEE
<link rel="stylesheet" type="text/css" href="/public/css/sl.css" media="screen" />
<link rel="stylesheet" href="/public/css/mediaboxAdvBlack.css" type="text/css" media="screen" />

<script type="text/javascript" src="http://ajax.googleapis.com/ajax/libs/mootools/1.2.4/mootools-yui-compressed.js"></script>
<script type="text/javascript" src="/public/js/mootools-moon.js"></script>
<script type="text/javascript" src="/public/js/slideshow-moon.js"></script>
<script type="text/javascript" src="/public/js/mediaboxAdv-1.2.0.js"></script>


<script type="text/javascript">
    //<![CDATA[
    window.addEvent('domready', function(){
        var data = {
                            <?php for($i=0; $i<count($gallery_images);$i++):   $image = $gallery_images[$i]  ?>
                                    '<?=$image['parent'];?>/mid/<?=$image['file'];?>': {
                                        caption: 'Нажмите для просмотра',
                                        href: "javascript:this.onclick(Mediabox.open('<?=$image['url'];?>','',''))",
                                        thumbnail: '<?=$image['parent'];?>/prev/<?=$image['file'];?>'
                                    }<?php if( ($i+1)!=count($gallery_images) ) {
                                        echo  ',';
                                    }
                                    if( ($i == 0) ) {
                                        $firstimage = '/images/loading.png';
                                        //$firstimage = '/gallery/data/gallery_video/'.$image['parent'].'/full/'.$image['file'];
                                        $firsturl = $image['url'];
                                }
                                endfor; ?>
                                };
                                var myShow = new Slideshow('show', data, {controller: true,  hu: '/gallery/data/gallery_video/', paused: true, linked: false, thumbnails: true, delay: 4000, height: 339, width: 509, duration: 750});
                            });
                            //]]>
</script>
<div id="show" class="slideshow">
    <a href="<?= $firsturl; ?>" id="url"  class="spacing"  title="cation">

        <img  src="<?= $firstimage;?>" width="506" height="339" alt="" />
    </a>
</div>


<h1><?php echo $this->content->title;?></h1>
<hr />
<?php echo $this->content->richtext;?>