<h2><ul style="float: left; margin: -15px;">
    <li <?php echo ($this->action == 'menu')?'class="adminmenuselected"':'class="adminmenu"'; ?> > <a  href="/mandi/menu">Menu</a></li>
    <li <?php echo ($this->action == 'property')?'class="adminmenuselected"':'class="adminmenu"'; ?> ><a href="/mandi/property" >Property</a></li>
    <li <?php echo ($this->action == 'news')?'class="adminmenuselected"':'class="adminmenu"'; ?> ><a href="/mandi/news" >News</a></li>
    <li <?php echo ($this->action == 'article')?'class="adminmenuselected"':'class="adminmenu"'; ?> ><a href="/mandi/article">Article</a></li>
</ul>
</h2>
