   <div class="footer_top">
<h5><?php echo $this->words['footerslogan'];?></h5>


<?php
foreach ($this->footermenu as $footermenu) :?>
<div class="footmn fl"> 
 <h4><?php echo $footermenu['item_'.$this->lang]; ?></h4>
    <ul>
        <?php
            $childfootermenu = Model_Menu::getMenu($footermenu->id, 1);
            foreach($childfootermenu as $footer) {
            $title = $footer['item_'.$this->lang];
            $link = $this->url(array('lang' => $this->lang,
                                     'title' => Local_String::translit($title),
                                     'menu_id' => $footer->id), 'menu');
        ?>
        <li><a href="<?php echo $link; ?>"><?php echo $title; ?></a></li>
        <?php } ?>
    </ul>
</div>
<?php
endforeach; ?>


<div class="clear"></div>
</div>	
<div class="foot_btm">	
		<div class="bookm fl" >
			Bookmark with&nbsp;|&nbsp;
               			<a title="Add to: Del.icio.us" onclick="window.open('http://del.icio.us/post?v=2&amp;url='+encodeURIComponent(location.href)+'&amp;notes=&amp;tags=&amp;title='+encodeURIComponent(document.title));return false;" href="http://del.icio.us/" target="_blank"  rel="nofollow">  
                           <img width="16" height="16" border="0" align="middle" alt="del.icio.us" src="/public/img/delicious.gif"> Delicious 
                        </a>&nbsp;|&nbsp;

                       	<a title="Add to: Digg" onclick="window.open('http://digg.com/submit?phase=2&amp;url='+encodeURIComponent(location.href)+'&amp;bodytext=&amp;tags=&amp;title='+encodeURIComponent(document.title));return false;" href="http://digg.com/" target="_blank"  rel="nofollow">               
                            <img width="16" height="16" border="0" align="middle" alt="Digg" src="/public/img/digg.gif"> Digg
                        </a>&nbsp;|&nbsp;                  
                        <a title="Add to: Facebook" onclick="window.open('http://www.facebook.com/sharer.php?u='+encodeURIComponent(location.href)+'&amp;t='+encodeURIComponent(document.title));return false;" href="http://facebook.com/" target="_blank"  rel="nofollow">
                            <img width="16" height="16" border="0" align="middle" alt="Facebook" src="/public/img/facebook.gif"> Facebook   
                        </a>&nbsp;|&nbsp;
						<a title="Add to: Google" onclick="window.open('http://www.google.com/bookmarks/mark?op=add&amp;bkmk='+encodeURIComponent(location.href)+'&amp;annotation=&amp;labels=&amp;title='+encodeURIComponent(document.title));return false;" href="http://www.google.com/" target="_blank"  rel="nofollow"> 
                            <img width="16" height="16" border="0" align="middle" alt="Google" src="/public/img/google.gif"> Google
                        </a>&nbsp;|&nbsp;
                        <a title="Add to: StumbleUpon" onclick="window.open('http://www.stumbleupon.com/submit?url='+encodeURIComponent(location.href)+'&amp;title='+encodeURIComponent(document.title));return false;" href="http://www.stumbleupon.com/" target="_blank"  rel="nofollow">
                            <img width="16" height="16" border="0" align="middle" alt="StumbleUpon" src="/public/img/stumbleupon.gif"> Stumbleupon 
                        </a>&nbsp;|&nbsp;
                        <a onclick="window.open('https://favorites.live.com/quickadd.aspx?marklet=1&amp;mkt=en-uk&amp;url='+encodeURIComponent(location.href)+'&amp;title='+encodeURIComponent(document.title)+';top=1','Live','toolbar=no,width=700,height=400'); return false;" href="http://live.com/" target="_blank" rel="nofollow">
                            <img width="16" height="16" border="0" align="middle" alt="Live" src="/public/img/windows.gif"> Live
                        </a> 
		</div>
		
		<div class="twi fr"> Follow us on <a href=""><img border="0" align="middle" alt="Twitter" src="/public/img/twi.png"></a></div>
		<div class="clear"></div>
		<div class="hr"></div>
		<div class="footmen2">
                    <p><a class="rbord" href="/en/Main-page-30.html">Hungarian property&nbsp;&nbsp;</a>&nbsp;
                    <a class="rbord" href="/en/New-projects-and-recently-build-68.html">Budapest property&nbsp;&nbsp;</a>&nbsp;
                    <a class="rbord" href="/en/Apartment-72.html">Balaton property&nbsp;&nbsp;</a>&nbsp;
                    <a class="rbord" href="/en/Reduced-to-sell-103.html">Special offer&nbsp;&nbsp;</a>&nbsp;
                    <a class="rbord" href="/en/Property-in-Vienna-76.html">Austria&nbsp;&nbsp;</a>&nbsp;
                    <a class="rbord" href="/en/General-Information-17.html">Eye on Hungary&nbsp;&nbsp;</a>&nbsp;
                    <a class="rbord" href="/en/Our-Services-80.html">Buying property in Budapest&nbsp;&nbsp;</a>&nbsp;
                    <a class="rbord" href="/en/Long-Term-Rentals-88.html">Rentals in Budapest&nbsp;&nbsp;</a>&nbsp;
                    <a href="/en/o-nas-81.html">Contact</a></p>
                </div>
		<div class="hr"></div>
                <div class="footmen3">
                    <div style="float: left;">
                        <p><a href="#">TOP OF THE PAGE</a>&nbsp;&nbsp;
                    <a href="#">USEFUL LINKS</a>&nbsp;&nbsp;
                    <a href="/<?php echo $this->lang;?>/sitemap.html">SITEMAP</a></p>
                    </div>
                    <div style="float: right;text-align: right;">
                        <p><a href="#">ИНФОРМАЦЫОННОЕ ПАРТНЕРСТВО</a></p>
                        <p style="font-family:arial,verdana,helvetica,sans-serif;font-size: 10px;color: #A4AEB0;">Hungary2Invest - Все права защищены<br />
                        При использовании материалов ссылка на сайт обязательна
                        </p>
                    </div>
                </div>
	</div>	
