<div id="subfooter">
<center>
    Сopyright &copy;&nbsp;<?php echo date('Y'); ?> DJ’s club PARTY ZONE </center>
</div>    
<script type="text/javascript">

    jQuery('.mancounter').click(function(){
       id = jQuery(this).attr('id');
       //jQuery(id + 'mandata').toggle();
       jQuery('#' + id + ' .mandata').toggle('slow'); 
       jQuery.get('/ajax/counter',{id:id},function(data){
            jQuery('#' + id + ' .mancnt').html('(' + data + ')').toggle();
       });
    });


  var _gaq = _gaq || [];
  _gaq.push(['_setAccount', 'UA-11548501-7']);
  _gaq.push(['_trackPageview']);

  (function() {
    var ga = document.createElement('script'); ga.type = 'text/javascript'; ga.async = true;
    ga.src = ('https:' == document.location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js';
    var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(ga, s);
  })();

</script>
