<h3 class="cont"><?php echo $this->words['h2itools'];?></h3>
<a class="dlista" href="http://conv.rbc.ru/" target="_blank">&bull; <?php echo $this->words['curconverter'];?></a>
<a class="dlista" href="http://maps.google.com/maps?f=q&source=s_q&hl=en&geocode=&q=Budapest,+Hungary&sll=37.0625,-95.677068&sspn=55.806079,79.013672&ie=UTF8&hq=&hnear=Budapest,+Hungary&z=11" target="_blank">&bull; <?php echo $this->words['mapofbudapest'];?></a>
<a class="dlista" href="http://maps.google.com/maps?f=q&source=s_q&hl=en&geocode=&q=Balaton,+Hungary&sll=47.498406,19.040758&sspn=0.376693,0.617294&ie=UTF8&hq=&hnear=Lake+Balaton,+Hungary&z=10" target="_blank">&bull; <?php echo $this->words['mapofbalaton'];?></a>
