<div  style="height: 241px; background: url('<?php echo $this->headerurl;?>') #0b0b0b   no-repeat center center;"></div>
<div class="langs fr" style="z-index: 10;position: absolute;">
    <a href="/">
    <img src="/public/img/ua-flag.gif" title="Українська" alt="Українська"></a>&nbsp;&nbsp;&nbsp;
    <a href="/ru/">
    <img src="/public/img/ru-flag.gif" title="Русский" alt="Русский">
    </a>
</div>

<!--<div style="z-index: 10; "><div  style="height: 241px; background: #0b0b0b url('<?php echo $this->headerurl;?>') no-repeat bottom right;"></div>
    <img src="<?php echo $this->headerurl;?>" />
</div>-->
