<div class="langs fr">
    <a href="/">
    <img src="/public/img/ua-flag.gif" title="Українська" alt="Українська"></a>&nbsp;&nbsp;&nbsp;
    <a href="/ru/">
    <img src="/public/img/ru-flag.gif" title="Русский" alt="Русский">
    </a>
</div>
<center>
    <div  style="   min-height:  240px;background: #0b0b0b url('<?php echo $this->headerurl;?>') no-repeat bottom right;"></div>
</center>
