  <div class="featured">
				<h3>Slogan</h3>
	</div>
	
	<div class="featured">
				<div style="display:none">

	<img src="http://thepioneerwoman.com/wp-content/themes/pioneerwoman/images/new_tabs/tab1-button.gif" alt="" />

	<img src="http://thepioneerwoman.com/wp-content/themes/pioneerwoman/images/new_tabs/tab2-button.gif" alt="" />

	<img src="http://thepioneerwoman.com/wp-content/themes/pioneerwoman/images/new_tabs/tab3-button.gif" alt="" />

	<img src="http://thepioneerwoman.com/wp-content/themes/pioneerwoman/images/new_tabs/tab4-button.gif" alt="" />

	<img src="http://thepioneerwoman.com/wp-content/themes/pioneerwoman/images/new_tabs/tab5-button.gif" alt="" />

	<img src="http://thepioneerwoman.com/wp-content/themes/pioneerwoman/images/new_tabs/tab1-button-on.png" alt="" />

	<img src="http://thepioneerwoman.com/wp-content/themes/pioneerwoman/images/new_tabs/tab2-button-on.png" alt="" />

	<img src="http://thepioneerwoman.com/wp-content/themes/pioneerwoman/images/new_tabs/tab3-button-on.png" alt="" />

	<img src="http://thepioneerwoman.com/wp-content/themes/pioneerwoman/images/new_tabs/tab4-button-on.png" alt="" />

	<img src="http://thepioneerwoman.com/wp-content/themes/pioneerwoman/images/new_tabs/tab5-button-on.png" alt="" />

</div>



			<div class="tabs2">
				<div class="tabstopbg">

					<div class="tabsbotbg" id="tabholder">
						<div id="tab1" class="tabblock">
							<p><img src="http://media.picfor.me/0011EE4E0/_large.jpg" alt="" /></p>							<div>
								<a href="http://thepioneerwoman.com/confessions/">
									<strong>Confessions of a Pioneer Woman</strong>
									<span><em>06-16-10</em><em class="text">Pink is Their Signature Color</em></span>
								</a>

							</div>
						</div>
						<div id="tab2" class="tabblock">
									<p>
			<img src="http://media.picfor.me/0011EE4E1/_large.jpg" alt="" />		</p>
		<div>
			<a href="http://thepioneerwoman.com/cooking/?p=6255"><strong>The Pioneer Woman Cooks!</strong>
    		<span>

    			<em>06-16-10</em>
    			<em class="text">Big and Strong</em>
    		</span>
    	</a>
    </div>
    						</div>
						<div id="tab3" class="tabblock">
									<p>

			<img src="http://thepioneerwoman.com/photography/files/2010/06/group1.jpg" alt="" />		</p>
		<div>
			<a href="http://thepioneerwoman.com/photography/?p=2767"><strong>Pioneer Woman Photography - Ree Drummond</strong>
    		<span>
    			<em>06-16-10</em>
    			<em class="text">YOUR Bug Photos: Group 1</em>
    		</span>

    	</a>
    </div>
    						</div>
						<div id="tab4" class="tabblock">
									<p>
			<img src="http://farm5.static.flickr.com/4045/4701647239_065e9f07b1_b.jpg" alt="" />		</p>
		<div>
			<a href="http://thepioneerwoman.com/homeandgarden/?p=2566"><strong>PW Home and Garden</strong>

    		<span>
    			<em>06-15-10</em>
    			<em class="text">Fresh Press</em>
    		</span>
    	</a>
    </div>
    						</div>
						<div id="tab5" class="tabblock">

									<p>
			<img src="http://thepioneerwoman.com/homeschooling/files/2010/06/saturn.jpg" alt="" />		</p>
		<div>
			<a href="http://thepioneerwoman.com/homeschooling/?p=3141"><strong>The Pioneer Woman - Homeschooling</strong>
    		<span>
    			<em>06-16-10</em>
    			<em class="text">Smartypants Winners!</em>

    		</span>
    	</a>
    </div>
    						</div>
						<div class="tabholder" id="tabset">
							<div>
								<a href="http://thepioneerwoman.com/confessions/" rel="#tab1" class="tab tab1 active"><strong class="conf">CONFESSIONS</strong></a>
								<a href="http://thepioneerwoman.com/cooking/" rel="#tab2" class="tab tab2"><strong class="cook">COOKING</strong></a>

								<a href="http://thepioneerwoman.com/photography/" rel="#tab3" class="tab tab4"><strong class="photo">PHOTOGRAPHY</strong></a>
								<a href="http://thepioneerwoman.com/homeandgarden/" rel="#tab4" class="tab tab3"><strong class="home">HOME &amp; GARDEN</strong></a>
								<a href="http://thepioneerwoman.com/homeschooling/" rel="#tab5" class="tab tab5"><strong class="school">HOMESCHOOLING</strong></a>
							</div>
						</div>
					</div>

				</div>
			</div>
	</div>
	
<div class="welcome">
     <div class="fl welk_main"><?php echo $this->title_text1;?> </div>
    <h2 class="welc"></h2>
    <?php echo $this->text1;?>
    <div class="clear"></div>
</div>


<h1 class="cont"><?php echo $this->words['main_proper-of-day'];?></h1>
<?php
foreach ($this->day_property as $proper) {
    echo $this->PropertyBox($proper, 'popularoftheday', $this->lang);
}
?>


<div class="clear"></div>

<div class="featured">
    <h5>Exhibition Property Shows</h5>

    <a class="prop" href="#nogo"><img alt="" title="" src="/public/img/adv_ban1.jpg"></a>
    <a class="prop" href="#nogo"><img alt="" title="" src="/public/img/adv_ban2.jpg"></a>
    <a class="prop" href="#nogo"><img alt="" title="" src="/public/img/adv_ban3.jpg"></a>
    <div class="clear"></div>

</div>


<h1 class="cont"><?php echo $this->words['main_popular-proper'];?></h1>

<?php
foreach ($this->popular_property as $proper) {
    echo $this->PropertyBox($proper, 'popular', $this->lang);
}
?>

<div class="clear"></div>


<div class="featured fl mr20">
<div class="banbig">
    <h3>Viena</h3>
    </div>
</div>

<div class="featured fl ">
<div class="banbig">
    <h3>Elite property</h3>
    </div>
</div>

<div class="featured fl mr20">
<div class="banbig">
    <h3>Hviz</h3>
    </div>
</div>

<div class="featured fl ">
<div class="banbig">
    <h3>Looking for Hungarian Holidays</h3>
    </div>
</div>

<div class="clear"></div>

<div class="featured">
    <h5>Partners</h5>

    <a class="part" href="#nogo"><img alt="" title="" src="/public/img/partn_logo1.jpg"></a>
    <a class="part" href="#nogo"><img alt="" title="" src="/public/img/partn_logo2.jpg"></a>
    <a class="part" href="#nogo"><img alt="" title="" src="/public/img/partn_logo3.jpg"></a>
    <a class="part" href="#nogo"><img alt="" title="" src="/public/img/partn_logo4.jpg"></a>
    <div class="clear"></div>

</div>




<br>


