<style>
    .small_1279201028 {
        FONT-SIZE:11px; FONT-FAMILY: arial
    }
    .norm_1279201028{
        FONT-SIZE:10px; FONT-FAMILY: arial
    }
    .txt_1279201028{
        FONT-SIZE:11px; FONT-FAMILY: Arial, Helvetica, sans-serif; font-weight: bold
    }
</style>
<h3>Курс Валют</h3>
<table border='0' cellspacing='0' cellpadding='3' style='border-color: #000000; border-width: 1; border-style: solid;BACKGROUND-COLOR: #FFFFFF;color:#000000;'>
    <tr align='center'  ><td>&nbsp;</td></tr>
    <tr align='center'>
        <td valign='top' colspan='2' align='left'>
            <span class='small_1279201028'>Венгерский форинт</span>
        </td>
        <td><a style='text-decoration:none;' href='http://prague-hotel.cc/' id='interchange_link_1279201028'><img src='http://prague-hotel.cc/img/HUF.gif' width='20' height='14' border='0' alt='Прага отель' title='Прага отель' style='text-decoration:none;'></a>
        </td>
    </tr>
    <tr align='center' title='Евро'><td>&nbsp;</td></tr>
        <tr align='center' title='Евро'>
                <td><img src='http://prague-hotel.cc/img/EUR.gif' width='20' height='14' border='0' alt='Евро'></td>
                <td class='norm_1279201028'>(EUR)</td>
                <td class='txt_1279201028'><b id='insert_rate_EUR_1279201028'>//-//</b></td>
        </tr>
        <tr align='center' title='Евро'><td>&nbsp;</td></tr>
        <tr align='center' title='Доллар США'>
            <td><img src='http://prague-hotel.cc/img/USD.gif' width='20' height='14' border='0' alt='Доллар США'></td><td class='norm_1279201028'>(USD)</td>
            <td class='txt_1279201028'><b id='insert_rate_USD_1279201028'>//-//</b></td>
    </tr>
    <tr align='center'>
        <td colspan='3'>
            <span id='rate_echo_kurs_insert_html_1279201028'></span>
            <script language='JavaScript' src='http://informer.prague-hotel.cc/script.php?go=get_informer&id=96841'>
            </script>
        </td>
    </tr>
</table>
