    <div style="float: left; width: 180px;">
        <div class="featured">
            <h3><?php echo $this->words['links_of_interests'];?></h3>



            <a  class="dlista"   href="http://www.hungarytourism.hu/" target="_blank">&bull; Official Tourism Homepage</a>
            <a class="dlista" href="http://www.gotohungary.com/" target="_blank">&bull; GoToHungary.com</a>
            <a class="dlista" href="http://www.malev.com/" target="_blank">&bull; Malev</a>
            <a class="dlista" href="http://www.ryanair.com/" target="_blank">&bull; Ryan Air</a>
            <a class="dlista"  href="http://www.helvetic.com/en" target="_blank">&bull; Helvetic-Airways</a>
            <a class="dlista"  href="http://www.en.balaton.ws/" target="_blank">&bull; Balaton-Homepage</a>
            <a class="dlista" href="http://www.west-balaton.hu/page.php?lng=en" target="_blank">&bull; West-Balaton.hu</a>
            <a class="dlista" href="http://www.heviz.hu/en_index.php" target="_blank">&bull; Heviz</a>
            <a class="dlista" href="http://www.gotohungary.com/events/events.php3?m=03" target="_blank">&bull; Balaton Event Planner</a>

            <div class="clear"></div>
        </div>

        <div class="featured">
            <?php echo $this->render('helpers/informer.phtml'); ?>
        </div>

        <div class="featured">
            <?php echo $this->render('helpers/h2itools.phtml'); ?>
        </div>
        <!--
        <div class="featured">
            <h3><?php echo $this->words['activities'];?></h3>
            <div class="descr">
                <img src="/public/img/property_act.png" alt="Activities"/>
                <ul>
                </ul>
            </div>
            <div class="clear"></div>
        </div>-->
        <!--
        <div class="featured">
            <h3><?php echo $this->words['balaton_schools'];?></h3>
            <div class="descr">
                <img src="/public/img/property_school.png" alt="Activities"/>
                <ul>
                    <li>link1</li>
                    <li>link2</li>
                    <li>link3</li>
                </ul>
            </div>
            <div class="clear"></div>
        </div>
        -->


    </div>