
<ul id="main_menu" clas="sub_menu_<?php echo $menu->idmenu."_".$this->lang;?>">
 <li>
     <a href="/<?php echo $this->lang; ?>/" class="menuitem"><?php echo $this->tr(NULL,$this->lang,'Головна'); ?></a>
 </li>
<?php
if (is_object($this->menu)) :
    // Обробляэмо обэкт меню
    foreach ($this->menu as $menu) :
        // Якщо у пункта меню немаэ предків виводимо в головне меню
        if ($menu->parent == 0) :
        // Шукаємо нащадків поточного пункта меню
        $menuchilds = Model_Menu::getAll($menu->idmenu, $this->lang);
        $haschilds = (is_object($menuchilds) && count($menuchilds) > 0) ? true : false; 
//        var_dump($menuchilds,$haschilds );
//        exit;
?>
        <li id="main_menu_<?php echo $menu->idmenu."_".$this->lang;?>">

            <?php
             
             if (count($menuchilds) < 1 ) {
                if ( $menu->idmenu == 16)  {
                    $url = $this->url(array('lang' => $this->lang), 'blog');
                } else {
                    $url =  $this->url(array('lang' => $this->lang,
                              'title' => $menu->getPageByMenu($this->lang),
                              'idpage' => $menu->idpage), 'page');
                }
             }
            ?>
            <a href="<?php echo $url; ?>" class="menuitem"><?php echo $menu->name;?></a>
            <?php
            // Якщо нащадки знайдені - виводимо
            if ($haschilds) :
                echo '<span class="menu_arrow"></span>';?>
            <ul id="sub_menu" >
                <?php foreach ($menuchilds as $child) :
                        if ( empty($child->idpage) ) {
                            $url = 'javascript:void(0)';
                        } else {
                            $url =  $this->url(array('lang' => $this->lang,
                                          'title' => $child->getPageByMenu($this->lang),
                                          'idpage' => $child->idpage), 'page');

                        }

                 ?>
                <li style="height: 32px;" id="sub_menu_<?php echo $menu->idmenu."_".$this->lang;?>" ><a href="<?php echo $url; ?>"  class="menuchilditem" style="padding: 5px 10px;"><?php echo $child->name; ?></a></li>
                <?php endforeach; ?>
            </ul>
            <?php endif; ?>
        </li>
        <?php
        endif;
    endforeach;
endif;
?>
</ul>
