<?php
if ($this->pageCount):
$url_ar = array('lang' => $this->lang);
?>

<table><tr><td>
<div class="paginationControl afl" style="display: inline;">
<!-- Previous page link -->
<?php if (isset($this->previous)):
    $url_ar['page'] = $this->previous;
 ?>
  <a href="<?php echo $this->url($url_ar,'blogpagination'); ?>">&lt; </a> |
<?php else:
    unset($url_ar['page']);
?>
  <span class="disabled2">&laquo;  </span> |
<?php endif; ?>
<!-- Numbered page links -->
<?php 
    foreach ($this->pagesInRange as $page):
    if ($page != $this->current):
            $url_ar['page'] = $page;
?>
            <a href="<?php echo $this->url($url_ar,'blogpagination'); ?>"><?php echo $page; ?></a> |
<?php
    else:
        unset($url_ar['page']);
        echo $page. " | ";
    endif;
    endforeach;
?>
<!-- Next page link -->
<?php
    if (isset($this->next)):
    $url_ar['page'] = $this->next;
?>
    <a href="<?php echo $this->url($url_ar,'blogpagination'); ?>"> &gt;</a>
<?php else: ?>
  <span class="disabled2"> &raquo;</span>
<?php endif; ?>
</div>
</td></tr></table>
<?php endif;

?>