 <div class="fl mainbox">
 
 <div class="day_prop">

    <a class="fl" href="<?php echo $this->link; ?>"><?php echo $this->title."  H<font size='1px'>2</font>I - ".$this->property->id; ?></a> <div  class="day_prop_txt fr">
    <span>
    <?php
    if ($this->property->size != '0') :?>
    <strong><?php echo $this->property->size;?> m&sup2;</strong>
    <?php else : ?>
	 
    <?php
    endif;?>
</span></div>
  <div class="clear"></div>
    <span class="fl"><?php echo $this->property->city;?> <?php echo $this->property->district;?>.</span>  <span class="fr"><?php echo $this->words['price_from'];?>:</span>
  <div class="clear"></div>
    

    <div  class="day_prop_txt">
        <span class="fl">
	    <?php
		if ($this->property->rooms != '0') :?>
            <?php echo $this->words['rooms'];?>: 
	      <span class="pr_prais"><?php echo $this->property->rooms;?>   </span>
	    <?php else : 
		 // echo "&nbsp;";
		endif;?>
	</span>
        <div class="pr_prais fr"><?php echo $this->property->euro;?> EUR</div>
      <div class="clear"></div>   
        <div class="fl">
            <span></span>
        </div>               
        <div class="pr_prais fr">
                    <?php if ( $this->property->forint > 0)  :  ?>
                <?php echo $this->property->forint;?> HUF
        <?php endif;?>
        </div>
    </div>
    
    
    
    
    
    <div>
    <a href="<?php echo $this->link; ?>">
        <img alt="<?php echo $this->title;?>" title="<?php echo $this->title;?>" src="<?php echo $this->property->getPicture('big');?>"></a>
    </div>

 
    <!--
    <div class="fr">
    <span>completion date:</span>
    <div class="pr_prais"><?php echo $this->property->completion_date;?></div>
    </div>
    -->
    <div class="clear"></div>
    <div class="descr"><?php echo $this->short;?></div>
   
    

</div>
     <div class="btn">
      <a href="<?php echo $this->link; ?>"><b><?php echo $this->words['details'];?> »</b></a>
    </div>
      <div class="clear"></div>
      </div>
