<?php
if ($this->showvideo) : ?>
<?php echo html_entity_decode(Model_Config::getConfig('mainvideo')); ?>
<?php
endif;

$page = array(
    35, 45, 46, 47, 48, 49
);

if (in_array($this->idpage, $page)) : ?>
<div class="sidebarservice">
    <br />
    <?php echo $this->tr(11, $this->lang, '<h2>Наші роботи</h2>'); ?>
    <br />
    <a href="/<?php echo $this->lang;?>/vesillya-45.html">
        <input type="button" class="lbut"  name="send"  value="<?php echo $this->tr(13, $this->lang, 'Весілля'); ?>"/></a>
    <br />
    <a href="/<?php echo $this->lang;?>/korporatyvy-46.html">
    <input type="button" class="lbut"  name="send"  value="<?php echo $this->tr(14, $this->lang, 'Корпоративи'); ?>"/></a>
    <br />
    <a href="/<?php echo $this->lang;?>/dni-narodzhennya-47.html">
    <input type="button" class="lbut"  name="send"  value="<?php echo $this->tr(15, $this->lang, 'Дні нарождення'); ?>"/></a>
    <br />
    <a href="/<?php echo $this->lang;?>/vypuskni-vechory-48.html">
    <input type="button" class="lbut"  name="send"  value="<?php echo $this->tr(16, $this->lang, 'Випускні вечори'); ?>"/></a>
    <br />
    <a href="/<?php echo $this->lang;?>/koncerty-49.html">
        <input type="button" class="lbut"  name="send"  value="<?php echo $this->tr(17, $this->lang, 'Концерти'); ?>"/></a>

</div>
<?php
endif; ?>

<img  src="/public/img/boxtop.png" />
<div class="sidebarcontact">
    <div class="sidebarbox" >
        <div id="msgcont" style="display:none;width:300px;height:110px;padding:5px;"></div>
        <br />
        <?php echo $this->tr(1, $this->lang, '<h2>Контакты</h2>'); ?>
        <br />
        <?php echo $this->tr(2, $this->lang, '<b>050 529 2714</b> - Андрій'); ?>
        <br />
        <?php echo $this->tr(3, $this->lang, '<b>050 507 6524</b> - Мирослав'); ?>

        <br /><br />
        <?php echo $this->tr(4, $this->lang, '<b>andrew.partyzone@gmail.com</b>'); ?>
        <br />
        <?php echo $this->tr(5, $this->lang, '<b>mirko.partyzone@gmail.com</b>'); ?>
        <br /><br /><hr />
        <br />
        <?php echo $this->tr(6, $this->lang, '<h2>Надіслати <br /> повідомлення</h2>'); ?>
        <br />
        <form name="sendmessage" action="/index/sendmessage" method="post" onsubmit="sendMessage();return false;" >
            <?php echo $this->tr(7, $this->lang, '<b>Відправник</b>'); ?>
            <br />
            <input name="sender" />
            <br />
            <?php echo $this->tr(8, $this->lang, 'Контактний номер<b>'); ?>
            <br />
            <input name="phone" />
            <br />
            <?php echo $this->tr(9, $this->lang, 'Повідомлення'); ?>
            <br />
            <textarea cols="20" rows="6"  name="message"></textarea>
            <br />
            <input type="submit"  class="slbut" name="send"  value="<?php echo $this->tr(10, $this->lang, 'Відправити'); ?>"/>
        </form>

    </div>
</div>
<div style="margin-top: -5px;">
<img  src="/public/img/boxbottom.png" />
</div>
<script type="text/javascript">
    function sendMessage() {
        var dataArray = jQuery('input[name=sender],input[name=phone],textarea[name=message]').serialize();
        var msglist = "";
        jQuery('input[name=send]').attr('disabled','disabled');
        jQuery.post(
        '/index/sendmessage',
        dataArray,
        function(data) {
            if (typeof data !== "error") {
                if (data['status'] == "success") {
                    msglist = "Вашого листа відправлено";
                } else if (data['status'] == "error") {
                    json = data['msg'];
                    for (elem in json) {
                        msg = "<ul>";
                        for (err in json[elem]) {
                            msg += "<li>" + json[elem][err] + "</li>";
                        }
                        msg += "</ul>";
                        msglist += msg;
                    }
                }
                msglist = msglist !== "" ? msglist : "Невизначена помилка!";
                jQuery("#msgcont").html(msglist).modal();
                jQuery('input[name=send]').attr('disabled','');
            }
        },
        'json'
    );    
    }
</script>

