<?php
if (Local_Base::isLogged()) :?>
<center><h1>Адміністративна панель </h1></center>
<div id="admin_menu">
<ul style="float: left; ">
  <li class="adminmenu<?php echo $this->menu_menu;?>">
    <a href="/admin/menu">Меню</a></li>

  <li class="adminmenu<?php echo $this->menu_page;?>">
    <a href="/admin/page">Сторінки</a></li>

  <li class="adminmenu<?php echo $this->menu_comment;?>">
    <a href="/admin/comment">Коментарі</a></li>

  <li class="adminmenu<?php echo $this->menu_gallery;?>">
      <a href="/admin/gallery">Галереї</a></li>

  <li class="adminmenu<?php echo $this->menu_video;?>">
      <a href="/admin/video">Відео</a></li>

  <li class="adminmenu<?php echo $this->menu_blogentry;?>">
      <a href="/admin/blogentry">Блог</a></li>
  
  <li class="adminmenu<?php echo $this->menu_translate;?>">
      <a href="/admin/translate">Переклади</a></li>

  <li class="adminmenu<?php echo $this->menu_medialib;?>">
      <a href="/admin/medialib">Медіа</a></li>  
  
  <li class="adminmenu<?php echo $this->menu_config;?>">
      <a href="/admin/config">Конфігурація</a></li>

  <li class="adminmenu">
      <a href="/admin/logout">Вийти</a></li>
</ul>
</div>
<?php
endif;