<?php
if (Local_Base::isLogged()) :?>
<center><h1>Адміністративна панель </h1></center>
<div id="admin_menu">
<ul style="float: left; ">
  <li class="adminmenu<?php echo $this->menu_menu;?>">
    <a href="/admin/menu">Меню</a></li>

  <li class="adminmenu<?php echo $this->menu_page;?>">
    <a href="/admin/page">Сторінки</a></li>

  <li class="adminmenu<?php echo $this->menu_gallery;?>">
      <a href="/admin/gallery">Галереї</a></li>

  <li class="adminmenu<?php echo $this->menu_blog;?>">
      <a href="/admin/blogentry">Блог</a></li>
  
  <li class="adminmenu<?php echo $this->menu_translate;?>">
      <a href="/admin/translate">Переклади</a></li>

  <li class="adminmenu">
      <a href="/admin/logout">Вийти</a></li>
</ul>
</div>
<?php
endif;