<div class="admin_content" >
    <form action="" method="post">
        <input type="submit" name="login_button" value="Поновити" id="admin_button" />
        <hr />
        <div class="field">
            <div class="field_name">Картинка для заднього фону :</div>
            <div >
                <input class="field_input" type="text" name="config[imagebackground]" value="<?php echo Model_Config::getConfig('imagebackground'); ?>" />
            </div>
        </div>
        <hr style="margin: 15px 0;" />
        <div class="field">
            <div class="field_name">код для  відео 237х240:</div>
            <div >
                <textarea style="margin-left: 145px; width: 315px;" rows="3"  name="config[mainvideo]" ><?php echo Model_Config::getConfig('mainvideo'); ?></textarea>
            </div>
        </div>
        <hr style="margin: 15px 0;" />
        <div class="field">
            <div class="field_name">Адмін пароль :</div>
            <div >
                <input class="field_input" type="text" name="config[adminpass]" value="<?php echo Model_Config::getConfig('adminpass'); ?>" />
            </div>
        </div>


    </form>
</div>