<div class="admin_content" >
    <form action="" method="post">
        <input type="submit" name="login_button" value="Поновити" id="admin_button" />
        <hr />
        <div class="field">
            <div class="field_name">Картинка для заднього фону :</div>
            <div >
                <input class="field_input" type="text" name="config[imagebackground]" value="<?php echo Model_Config::getConfig('imagebackground'); ?>" />
            </div>
        </div>
    </form>
</div>