<form action="/admin/savemenu" method="post" >
    <div class="field">
        <div class="field_name">Назва :</div>
        <div >
            <input class="field_input" type="text" name="name"   value="<?php echo $this->menudata->name; ?>" />
            <input  type="hidden" name="idmenu" value="<?php echo $this->item; ?>" />
        </div>
    </div>

    <div class="field">
        <div class="field_name">Мова :</div>
        <div >
            <select id="lang" class="field_input" name="lang" onchange="window.location='/admin/menu/item/' + <?php echo $this->item;?> +  '/lang/' + $('#lang').val() ">
            <?php
            foreach ($this->langs as $lang) : ?>
            <option value="<?php echo $lang; ?>" <?php echo ($this->lang == $lang)?'selected="selected"':''; ?>>
                <?php echo $lang; ?>
            </option>
            <?php
            endforeach;   ?>
        </select>
        </div>
    </div>


    <div class="field">
        <div class="field_name">Меню :</div>
        <select class="field_input" name="parent"   >
            <option value="0">Головне Меню</option>
            <?php
            if (is_object($this->mainmenu)) :
                foreach ($this->mainmenu as $menu)  :
                    if ($menu->idmenu == $this->menudata->idmenu ) { continue; }    ?>
                    <option
                    <?php echo ($menu->idmenu == $this->menudata->parent)?'selected="selected"':''; ?>
                value="<?php echo $menu->idmenu; ?>" >
                    <?php echo $menu->name; ?></option>
                <?php
                endforeach; endif; ?>
        </select>
    </div>
    <div class="field">
        <div class="field_name">Сторінка :</div>
        <select class="field_input" name="idpage"   >
            <option value="0">Вибрати сторінку</option>
            <?php
            if (is_object($this->pages)) :
                foreach ($this->pages as $page)  : ?>
            <option <?php echo ($page->idpage == $this->menudata->idpage)?'selected="selected"':''; ?>
                value="<?php echo $page->idpage; ?>" >
                    <?php echo $page->title; ?></option>
                <?php
                endforeach; endif; ?>
        </select>
    </div>

    <div class="field">
        <div class="field_name">Редагування :</div>
            <select class="field_input" name="blockedit" >
                <option value="unblock" <?php echo ($this->menudata->blockedit == 'unblock')?'select="selected"':''; ?> >Не Блокувати</option>>
                <option value="block" <?php echo ($this->menudata->blockedit == 'block')?'selected="selected"':''; ?>>Блокувати</option>>
            </select>
    </div>
    
    <input type="submit" name="login_button" value="<?php echo $this->buttonname;?>" id="admin_button" />
</form>