<?php $this->ckeditor = 'ckeditor'; ?>
<div style="margin-left:20px;">

<?php
if ( $this->item != 'new') : ?>
 <div id="admin_page_thumb" >
     <img id="curThumb" src="/public/img/blog/thumb/<?php echo $this->escape($this->item); ?>.jpg" />
     <div style="position: absolute; bottom: 0;">
        <div class="fieldset flash" id="fsUploadProgress">
            <span class="legend">Черга завантаження</span>
        </div>
        <div id="divStatus">0 Файлів завантажено</div>
        <div style="margin-bottom: 6px;">
            <span id="spanButtonPlaceHolder"></span>
            <input id="btnCancel" type="button" value="Скасувати" onclick="swfu.cancelQueue();" disabled="disabled" style="position: absolute;margin-left: 2px; font-size: 8pt; height: 29px;" />
        </div>
     </div>
 </div>
 <?php
 endif;?>
<form action="<?php echo $this->actionname;?>" method="post">
    <input id="<?php echo $this->idname;?>" type="hidden" name="<?php echo $this->idname;?>"
           value="<?php echo $this->escape($this->item); ?>" />
    <div class="field">
    <div class="field_name">Назва: </div>
    <div><input id="title" class="field_input" type="text" name="title"
                value="<?php echo $this->escape($this->data->title); ?>" /></div>
    </div>
    <div class="field">
    <div class="field_name">Ключові слова: </div>
    <div><input id="keyword" class="field_input" type="text" name="keyword"
                value="<?php echo $this->escape($this->data->keyword); ?>" /></div>
    </div>
    <div class="field">
    <div class="field_name">Опис: </div>
    <div><input id="description" class="field_input" type="text" name="description" 
                value="<?php echo $this->escape($this->data->description); ?>" /></div>
    </div>

    <div class="field">
    <div class="field_name">Мови: </div>
    <div><select id="lang" class="field_input" name="lang" onchange="window.location='/admin/blogentry/item/' + <?php echo $this->item;?> +  '/lang/' + $('#lang').val() ">
            <?php
            foreach ($this->langs as $lang) : ?>
            <option value="<?php echo $lang; ?>" <?php echo ($this->lang == $lang)?'selected="selected"':''; ?>>
                <?php echo $lang; ?>
            </option>
            <?php
            endforeach;   ?>
        </select>
    </div></div>
    <div style="height: 80px;"></div>
    <div class="field">
    <div class="field_name">Контент: </div><br /><br />
    <div><textarea class="field_input" id="richtext" cols="30" rows="5" name="richtext">
            <?php echo $this->data->richtext; ?>
        </textarea></div>
    </div>
    <input id="admin_button"  type="submit" name="submit" value="Зберегти" />
</form>
</div>


<?php echo $this->setupEditor('richtext'); ?>

<?php
if ( $this->item != 'new') : ?>

<script type="text/javascript" src="/public/swfupload/swfupload.js"></script>
<script type="text/javascript" src="/public/js/swfupload.queue.js"></script>
<script type="text/javascript" src="/public/js/fileprogress.js"></script>
<script type="text/javascript" src="/public/js/handlers.js"></script>
<script type="text/javascript">
    var swfu;

    window.onload = function() {
        var settings = {
            flash_url : "/public/swfupload/swfupload.swf",
            upload_url: "/ajax/thumbupload/type/blog/item/<?php echo $this->item; ?>",
            post_params: {"PHPSESSID" : "<?php echo session_id(); ?>"},
            file_size_limit : "100 MB",
            file_types : "*.*",
            file_types_description : "Всі файли",
            file_upload_limit : 100,
            file_queue_limit : 0,
            custom_settings : {
                progressTarget : "fsUploadProgress",
                cancelButtonId : "btnCancel"
            },
            debug: false,

            // Button settings
            button_image_url: "/public/img/uploadbtn.png",
            button_width: "172",
            button_height: "30",
            button_placeholder_id: "spanButtonPlaceHolder",
            button_text: '<span class="theFont">Завантажити</span>',
            button_text_style: ".theFont { pointer:cursor; font-size: 19; color: #dddddd;text-decoration: none; font-weight: bold;}",
            button_text_left_padding: 12,
            button_text_top_padding: 3,

            // The event handler functions are defined in handlers.js
            file_queued_handler : fileQueued,
            file_queue_error_handler : fileQueueError,
            file_dialog_complete_handler : fileDialogComplete,
            upload_start_handler : uploadStart,
            upload_progress_handler : uploadProgress,
            upload_error_handler : uploadError,
            upload_success_handler : uploadSuccess,
            upload_complete_handler : uploadComplete,
            queue_complete_handler : queueComplete	// Queue plugin event
        };

        swfu = new SWFUpload(settings);
    };

    function afterUpload() {
        d = new Date();
        $("#curThumb").attr("src", "/public/img/blog/thumb/<?php echo $this->item; ?>.jpg?"+d.getTime());
    }

    $(document).ready(function() {
    
    });
</script>
<?php
endif;?>