<form action="/admin/savegallery" method="post" >
    <div class="field">
        <div class="field_name">Назва :</div>
        <div >
            <input class="field_input" type="text" name="name" value="<?php echo $this->data->name; ?>" />
            <input  type="hidden" name="idgallery" value="<?php echo $this->item; ?>" />
        </div>
    </div>

    <input type="submit"  value="<?php echo ($this->item == 'new')?'Додати':'Поновити';?>" id="admin_button" />
</form>

<?php
if ( $this->item != 'new' ) : ?>
<div id="content">
    <form id="form1" action="/mandi/imgupload/item/<?php echo $this->item; ?>" method="post" enctype="multipart/form-data">
        <div class="fieldset flash" id="fsUploadProgress">
            <span class="legend">Черга завантаження</span>
        </div>
        <div id="divStatus">0 Файлів завантажено</div>
        <div style="margin-bottom: 6px;">
            <span id="spanButtonPlaceHolder"></span>
            <input id="btnCancel" type="button" value="Скасувати" onclick="swfu.cancelQueue();" disabled="disabled" style="position: absolute;margin-left: 2px; font-size: 8pt; height: 29px;" />
        </div>

    </form>
</div>
<div class="photolist"></div>



<script type="text/javascript" src="/public/swfupload/swfupload.js"></script>
<script type="text/javascript" src="/public/js/swfupload.queue.js"></script>
<script type="text/javascript" src="/public/js/fileprogress.js"></script>
<script type="text/javascript" src="/public/js/handlers.js"></script>
<script type="text/javascript">
    var swfu;

    window.onload = function() {
        var settings = {
            flash_url : "/public/swfupload/swfupload.swf",
            upload_url: "/ajax/imgupload/item/<?php echo $this->item; ?>",
            post_params: {"PHPSESSID" : "<?php echo session_id(); ?>"},
            file_size_limit : "100 MB",
            file_types : "*.*",
            file_types_description : "Всі файли",
            file_upload_limit : 100,
            file_queue_limit : 0,
            custom_settings : {
                progressTarget : "fsUploadProgress",
                cancelButtonId : "btnCancel"
            },
            debug: false,

            // Button settings
            button_image_url: "/public/img/uploadbtn.png",
            button_width: "172",
            button_height: "30",
            button_placeholder_id: "spanButtonPlaceHolder",
            button_text: '<span class="theFont">Завантажити</span>',
            button_text_style: ".theFont { pointer:cursor; font-size: 19; color: #dddddd;text-decoration: none; font-weight: bold;}",
            button_text_left_padding: 12,
            button_text_top_padding: 3,

            // The event handler functions are defined in handlers.js
            file_queued_handler : fileQueued,
            file_queue_error_handler : fileQueueError,
            file_dialog_complete_handler : fileDialogComplete,
            upload_start_handler : uploadStart,
            upload_progress_handler : uploadProgress,
            upload_error_handler : uploadError,
            upload_success_handler : uploadSuccess,
            upload_complete_handler : uploadComplete,
            queue_complete_handler : queueComplete	// Queue plugin event
        };

        swfu = new SWFUpload(settings);
    };

    function afterUpload() {
        
        $.get('/ajax/getimg/item/' + '<?php echo $this->item; ?>' , function(data){
           // var imgs = eval('(' + data + ')');
            $('.photolist').html(data);
        });
    }

    $(document).ready(function() {
        $.get('/ajax/getimg/item/' + '<?php echo $this->item; ?>', function(data){
            // var imgs = eval('(' + data + ')');
            $('.photolist').html(data);
        });
    });
</script>

<?php
endif; ?>