<?php $this->ckeditor = 'ckeditor'; ?>
<div style="margin-left:20px;">
<form action="<?php echo $this->actionname;?>" method="post">
    <input id="<?php echo $this->idname;?>" type="hidden" name="<?php echo $this->idname;?>"
           value="<?php echo $this->escape($this->item); ?>" />
    <div class="field">
    <div class="field_name">Назва: </div>
    <div><input id="title" class="field_input" type="text" name="title"
                value="<?php echo $this->escape($this->data->title); ?>" /></div>
    </div>
    <div class="field">
    <div class="field_name">URL: </div>
    <div><input id="url" class="field_input" type="text" name="url"
                value="<?php echo $this->escape($this->data->url); ?>" /></div>
    </div>
    <div class="field">
    <div class="field_name">Ключові слова: </div>
    <div><input id="keyword" class="field_input" type="text" name="keyword"
                value="<?php echo $this->escape($this->data->keyword); ?>" /></div>
    </div>
    <div class="field">
    <div class="field_name">Опис: </div>
    <div><input id="description" class="field_input" type="text" name="description" 
                value="<?php echo $this->escape($this->data->description); ?>" /></div>
    </div>

    <div class="field">
    <div class="field_name">Мови: </div>
    <div><select id="lang" class="field_input" name="lang" onchange="window.location='/admin/page/item/' + <?php echo $this->item;?> +  '/lang/' + $('#lang').val() ">
            <?php
            foreach ($this->langs as $lang) : ?>
            <option value="<?php echo $lang; ?>" <?php echo ($this->lang == $lang)?'selected="selected"':''; ?>>
                <?php echo $lang; ?>
            </option>
            <?php
            endforeach;   ?>
        </select>
    </div></div>

    <div class="field">
    <div class="field_name">Контент: </div><br /><br />
    <div><textarea class="field_input" id="richtext" cols="30" rows="5" name="richtext">
            <?php echo $this->data->richtext; ?>
        </textarea></div>
    </div>
    <input id="admin_button" type="submit" name="submit" value="Зберегти" />
</form>
</div>
<?php echo $this->setupEditor('richtext'); ?>