<link href="/public/css/colorbox/colorbox.css" rel="stylesheet" />
<script src="/public/js/colorbox/jquery.colorbox-min.js"></script>
<div style="overflow-y: scroll;overflow-x: hidden; height: 700px;">
<center> <h2>Тут медія смітник</h2> </center>
<table>
    <tr>
        <td></td>
        <td></td>
    </tr>
    <tr>
        <td>
            <div id="imggallery">Завантажую картинки...</div>
        </td>
    </tr>
</table>
</div>
<script  type="text/javascript">
 jQuery(document).ready(function(){
     
     getImages();
 });
  function getImages() {
     jQuery.get("/ajax/getallgalimages",
            function(data){
             jQuery("#imggallery").html(data);
             $("a.gallery").colorbox();     
            });
           
 }

 function delImage(id, type){
   jQuery.post("/ajax/delgalimg",
    { item :id,
      type : type
    });
   getImages();   
   

   
 }
</script>