
    <div class="admin_submenu" >
        <div class="menulist" >
            <a href="/admin/menu/item/new">Додати пункт меню</a>
        </div>

        <div> ----- </div>
        <?php
        if (is_object($this->mainmenu)) :
        foreach ($this->mainmenu as $menu)  : ?>
            <div class="menulist" ><a href="/admin/menu/item/<?php echo $menu->idmenu; ?>">
                <?php echo $menu->name; ?></a>&nbsp;&nbsp;
                <a href="/admin/menu/item/<?php echo $menu->idmenu; ?>/delete/1">X</a></div>
                <ul>
                <?php
                if ( ($menu->idmenu == $this->curmenu) && is_object($this->submenu) ) :
                foreach ($this->submenu as $submenu)  : ?>
                   <li class="menulist"><a href="/admin/menu/item/<?php echo $submenu->idmenu; ?>">
                <?php echo $submenu->name; ?></a>&nbsp;&nbsp;
                   <a href="/admin/menu/item/<?php echo $submenu->idmenu; ?>/delete/1">X</a>
                   </li>
                <?php
                endforeach; endif; ?>
                </ul>
            
        <?php
        endforeach; endif; ?>
    </div>

    <div class="admin_content" >

        <?php
        switch ($this->item) {
            case 'new' :
                  echo   '<h2 class="admin_title">Новий пункт меню</h2>';
                  break;

           default : echo '<h2 class="admin_title">Редагувати пункт меню</h2>';
                  break;

        }
        echo $this->render('admin/editmenu.phtml');
        ?>

    </div>


