<div class="admin_submenu" >
    <div class="menulist" >
        <a href="/admin/page/item/new">Додати Сторінку</a>
    </div>
    <div> ----- </div>
    <?php
    if (is_object($this->pages)) :
    foreach ($this->pages as $item)  : ?>
        <div class="menulist" ><a href="/admin/page/item/<?php echo $item->idpage; ?>">
            <?php echo $item->title; ?></a>&nbsp;&nbsp;
            <a href="/admin/page/item/<?php echo $item->idpage; ?>/delete/1"
               onclick="if(confirm('Впевнені, що хочете видалити?')) {return true;} else {return false;}">X</a></div>
    <?php
    endforeach; endif; ?>
</div>
<div class="admin_content"  style="height: 430px; overflow-y: scroll; overflow-x: hidden;" >
    <?php
    switch ($this->item) {
        case 'new' :
              echo   '<h2 class="admin_title">Створити сторінку</h2>';
              break;
       default : echo '<h2 class="admin_title">Редагувати сторінку</h2>';
              break;
    }
    echo $this->render('admin/editpage.phtml');
    ?>
</div>