<div class="admin_submenu" style="height: 430px; overflow-y: scroll; overflow-x: hidden;">
        <div class="menulist" >
            <a href="/admin/video/item/new">Додати Галерею</a>
        </div>

        <div> ----- </div>
        <?php
        if (is_object($this->video)) :
        foreach ($this->video as $item)  : ?>
            <div class="menulist" ><a href="/admin/video/item/<?php echo $item->idgallery; ?>">
                <?php echo $item->name; ?></a>&nbsp;&nbsp;
                <a href="/admin/video/item/<?php echo $item->idgallery; ?>/delete/1"
                   onclick="if(confirm('Впевнені, що хочете видалити?')) {return true;} else {return false;}">X</a></div>
        <?php
        endforeach; endif; ?>
</div>

<div class="admin_content" >

        <?php
        switch ($this->item) {
            case 'new' :
                  echo   '<h2 class="admin_title">Створити галерею</h2>';
                  break;

           default : echo '<h2 class="admin_title">Редагувати галерею</h2>';
                     break;

        }
        echo $this->render('admin/editvideo.phtml');
        ?>

</div>